# Project: Project1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o h/itineraire.o
LINKOBJ  = main.o h/itineraire.o
LIBS     = -L"D:/Programmes/Dev-Cpp/MinGW64/gcc-6-win64/lib" -L"D:/Programmes/Dev-Cpp/MinGW64/gcc-6-win64/x86_64-w64-mingw32/lib" -static-libstdc++ -static-libgcc
INCS     = -I"D:/Programmes/Dev-Cpp/MinGW64/gcc-6-win64/include" -I"D:/Programmes/Dev-Cpp/MinGW64/gcc-6-win64/x86_64-w64-mingw32/include" -I"D:/Programmes/Dev-Cpp/MinGW64/gcc-6-win64/lib/gcc/x86_64-w64-mingw32/6.2.1/include"
CXXINCS  = -I"D:/Programmes/Dev-Cpp/MinGW64/gcc-6-win64/include" -I"D:/Programmes/Dev-Cpp/MinGW64/gcc-6-win64/x86_64-w64-mingw32/include" -I"D:/Programmes/Dev-Cpp/MinGW64/gcc-6-win64/lib/gcc/x86_64-w64-mingw32/6.2.1/include"
BIN      = Project1.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

h/itineraire.o: h/itineraire.cpp
	$(CPP) -c h/itineraire.cpp -o h/itineraire.o $(CXXFLAGS)
